name: libarp
on: [push, pull_request]

jobs:
  build-ubuntu-gcc:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.ACCESS_TOKEN}}
        submodules: recursive
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
      env:
        CC: gcc
    - name: build
      run: cmake --build build --parallel 8
    - name: archive
      uses: actions/upload-artifact@v1
      with:
        name: libarp_dist_linux
        path: build/dist/

  build-ubuntu-clang:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.ACCESS_TOKEN}}
        submodules: recursive
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
      env:
        CC: clang
    - name: build
      run: cmake --build build --parallel 8
    - name: archive
      uses: actions/upload-artifact@v1
      with:
        name: libarp_dist_linux
        path: build/dist/

  build-windows:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.ACCESS_TOKEN}}
        submodules: recursive
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION=10.0.19041.0 -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=Debug ..
    - name: build
      run: cmake --build build --parallel 8
    - name: archive
      uses: actions/upload-artifact@v1
      with:
        name: libarp_dist_windows
        path: build/dist/
